<?php

declare(strict_types=1);

/**
 * Writes docs/README_FUNCTION_REFERENCE.generated.md — full function list with PHP signatures and API summaries.
 * Requires: composer install, demo/includes/method_summaries.json
 */

$root = dirname(__DIR__);
require $root . '/vendor/autoload.php';
require $root . '/demo/includes/explorer.php';

$summariesPath = $root . '/demo/includes/method_summaries.json';
$summaries = [];
if (is_readable($summariesPath)) {
    $raw = file_get_contents($summariesPath);
    if ($raw !== false) {
        $summaries = json_decode($raw, true) ?: [];
    }
}

function reflectTypeStr(?ReflectionType $t): string
{
    if ($t === null) {
        return '';
    }
    if ($t instanceof ReflectionNamedType) {
        $n = $t->getName();
        $pref = $t->allowsNull() && $n !== 'mixed' ? '?' : '';

        return $pref . $n;
    }
    if ($t instanceof ReflectionUnionType) {
        $parts = [];
        foreach ($t->getTypes() as $u) {
            $parts[] = $u instanceof ReflectionNamedType ? $u->getName() : 'mixed';
        }

        return implode('|', $parts);
    }

    return '';
}

/** Escape text inside HTML <code> (do not encode `>` so PHP `->` stays readable). */
function esc_code(string $s): string
{
    return str_replace(['&', '<'], ['&amp;', '&lt;'], $s);
}

function formatDefault(mixed $v): string
{
    if ($v === []) {
        return '[]';
    }
    if (is_array($v)) {
        return json_encode($v, JSON_THROW_ON_ERROR | JSON_UNESCAPED_SLASHES);
    }
    if ($v instanceof stdClass) {
        return '(object) []';
    }
    if (is_string($v)) {
        return "'" . addcslashes($v, "'\\") . "'";
    }
    if (is_bool($v)) {
        return $v ? 'true' : 'false';
    }
    if ($v === null) {
        return 'null';
    }

    return var_export($v, true);
}

/** @return list<string> */
function formatSignatureParams(ReflectionMethod $m): array
{
    $out = [];
    foreach ($m->getParameters() as $p) {
        $ts = reflectTypeStr($p->getType());
        $prefix = $ts !== '' ? $ts . ' ' : '';
        $name = '$' . $p->getName();
        if ($p->isOptional() && $p->isDefaultValueAvailable()) {
            try {
                $def = $p->getDefaultValue();
                $out[] = $prefix . $name . ' = ' . formatDefault($def);
            } catch (ReflectionException) {
                $out[] = $prefix . $name;
            }
        } else {
            $out[] = $prefix . $name;
        }
    }

    return $out;
}

$lines = [
    '<!-- Generated by scripts/generate_readme_function_reference.php — do not edit by hand -->',
    '',
    '## All functions (usage)',
    '',
    'Each call returns a decoded JSON **array** (the API response root). Throws `Ghostcompiler\\Hetzner\\ApiException` on HTTP errors.',
    '',
    '**Pattern:** `$hc->{client}->{methodName}(...arguments...)` where `{client}` is a property of [`HetznerClient`](src/HetznerClient.php).',
    '',
];

$map = hetzner_demo_client_map();
ksort($map);

foreach ($map as $prop => $class) {
    $classBase = basename(str_replace('\\', '/', $class));
    $lines[] = '### `' . $prop . '` — `' . $classBase . '`';
    $lines[] = '';
    $lines[] = '| PHP usage | HTTP | Path | What it does |';
    $lines[] = '| --- | --- | --- | --- |';

    foreach (hetzner_demo_public_methods($class) as $method) {
        $mname = $method->getName();
        $args = formatSignatureParams($method);
        $usagePlain = '$hc->' . $prop . '->' . $mname . '(' . implode(', ', $args) . ')';
        // HTML <code> avoids breaking Markdown tables when types contain "|" (e.g. int|string).
        $usageCell = '<code>' . esc_code($usagePlain) . '</code>';

        $meta = $summaries[$prop][$mname] ?? null;
        $http = is_array($meta) ? ($meta['http'] ?? '') : '';
        $path = is_array($meta) ? ($meta['path'] ?? '') : '';
        $summ = is_array($meta) ? ($meta['summary'] ?? '') : '';
        if ($summ === '') {
            $summ = '_See [Hetzner API docs](https://docs.hetzner.cloud/reference/cloud)._';
        }

        $pathCell = $path !== '' ? '<code>' . esc_code($path) . '</code>' : '—';
        $summEsc = str_replace('|', '\\|', $summ);

        $lines[] = '| ' . $usageCell . ' | ' . $http . ' | ' . $pathCell . ' | ' . $summEsc . ' |';
    }

    $lines[] = '';
}

$outFile = $root . '/docs/README_FUNCTION_REFERENCE.generated.md';
if (! is_dir(dirname($outFile))) {
    mkdir(dirname($outFile), 0755, true);
}
file_put_contents($outFile, implode("\n", $lines) . "\n");

echo "Wrote {$outFile}\n";
